server:
  port: 8989
  servlet:
    context-path: /ems
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  profiles:
    active: product
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:com/haku/dao/impl/*.xml
  type-aliases-package: com.haku.entity
